CREATE DATABASE IF NOT EXISTS Logistix;

USE Logistix;

CREATE TABLE IF NOT EXISTS Inventory (
    Code INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SKU VARCHAR(80) DEFAULT NULL,
    Name VARCHAR(150) NOT NULL,
    Brand VARCHAR(100) DEFAULT NULL,
    Manufacturer VARCHAR(120) DEFAULT NULL,
    Models VARCHAR(100) DEFAULT NULL,
    Types VARCHAR(80) NOT NULL,
    Categories VARCHAR(100) NOT NULL,
    Measures VARCHAR(50) NOT NULL,
    Barcode VARCHAR(100) DEFAULT NULL,
    ReorderLevel DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    OpeningQuantity DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    Cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    Price DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    Location VARCHAR(120) DEFAULT NULL,
    Status VARCHAR(40) DEFAULT 'Active',
    Description TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Code)
);

CREATE TABLE IF NOT EXISTS suppliers (
    TINumber VARCHAR(50) NOT NULL,
    Type VARCHAR(80) DEFAULT NULL,
    SUName VARCHAR(150) NOT NULL,
    ContactPerson VARCHAR(150) DEFAULT NULL,
    BName VARCHAR(120) NOT NULL,
    ACNumber VARCHAR(80) NOT NULL,
    Phone VARCHAR(40) DEFAULT NULL,
    Email VARCHAR(150) DEFAULT NULL,
    Address VARCHAR(180) DEFAULT NULL,
    City VARCHAR(100) DEFAULT NULL,
    Country VARCHAR(100) DEFAULT NULL,
    PaymentTerms VARCHAR(50) DEFAULT NULL,
    CreditLimit DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    Status VARCHAR(40) DEFAULT 'Active',
    Notes TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (TINumber)
);

CREATE TABLE IF NOT EXISTS customers (
    CustomerID VARCHAR(50) NOT NULL,
    Type VARCHAR(80) DEFAULT NULL,
    CName VARCHAR(150) NOT NULL,
    ContactPerson VARCHAR(150) DEFAULT NULL,
    BName VARCHAR(120) DEFAULT NULL,
    ACNumber VARCHAR(80) DEFAULT NULL,
    Phone VARCHAR(40) DEFAULT NULL,
    Email VARCHAR(150) DEFAULT NULL,
    Address VARCHAR(180) DEFAULT NULL,
    City VARCHAR(100) DEFAULT NULL,
    Country VARCHAR(100) DEFAULT NULL,
    PaymentTerms VARCHAR(50) DEFAULT NULL,
    CreditLimit DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    Status VARCHAR(40) DEFAULT 'Active',
    Notes TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (CustomerID)
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    POID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SupplierName VARCHAR(150) DEFAULT NULL,
    SupplierTIN VARCHAR(50) DEFAULT NULL,
    InvoiceNumber VARCHAR(80) DEFAULT NULL,
    InvoiceDate DATE DEFAULT NULL,
    PaymentOption VARCHAR(50) DEFAULT NULL,
    ItemCode INT UNSIGNED NOT NULL,
    ItemName VARCHAR(150) NOT NULL,
    Quantity DECIMAL(12, 2) NOT NULL DEFAULT 1.00,
    Cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (POID),
    INDEX (ItemCode)
);
